// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrnaMvc.Data;

#nullable disable

namespace UrnaMvc.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221110143656_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UrnaMvc.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_registro");

                    b.Property<int>("Legenda")
                        .HasColumnType("int")
                        .HasColumnName("legenda");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NomeVice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome_vice");

                    b.HasKey("Id");

                    b.ToTable("candidate", (string)null);
                });

            modelBuilder.Entity("UrnaMvc.Models.Voting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("DataVoto")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_voto");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("voting", (string)null);
                });

            modelBuilder.Entity("UrnaMvc.Models.Voting", b =>
                {
                    b.HasOne("UrnaMvc.Models.Candidate", "Candidate")
                        .WithMany("ListaVotos")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("UrnaMvc.Models.Candidate", b =>
                {
                    b.Navigation("ListaVotos");
                });
#pragma warning restore 612, 618
        }
    }
}
